spring.application.name=auth-service

server.port=4005

# spring.datasource.url=jdbc:postgresql://localhost/testdb
# spring.datasource.username=admin_viewer
# spring.datasource.password=password
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.datasource.driver-class-name=org.postgresql.Driver