spring.application.name=billing-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://billing-service-db:5432/billingdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_viewer}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=4002
grpc.server.port=9095