spring.application.name=patient-service

# H2 Database Configuration (for development/testing)- Uncomment for in-memory database setup
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console


# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.username=admin_viewer
# spring.datasource.password=password
# spring.datasource.driver-class-name=org.h2.Driver

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update

# spring.sql.init.mode=always

server.port=4000

# billing.service.address=localhost
# billing.service.port=9095

logging.level.root=INFO

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

