server:
  port: 4006

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://appointment-service-db:5432/appointmentdb}
    username: ${SPRING_DATASOURCE_USERNAME:admin_viewer}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  sql:
    init:
      mode: always

kafka:
  bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
